name:                mecab
version:             0.4.0.1
github:              "nobsun/mecab"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2009-2021 Hideyuki Tanaka, 2021 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/mecab#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- text

library:
  source-dirs: src

executables:
  mecab:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - mecab

# tests:
#   mecab-test:
#     main:                spec.hs
#     source-dirs:         test
#     # ghc-options:
#     # - -threaded
#     # - -rtsopts
#     # - -with-rtsopts=-N
#     dependencies:
#     - mecab
#     - hspec
#     - main-tester

#   mecab-doctest:
#     main:                doctests.hs
#     source-dirs:         test
#     # ghc-options:
#     # - -threaded
#     # - -rtsopts
#     # - -with-rtsopts=-N
#     dependencies:
#     - mecab
#     - doctest
